Add Aggregator and Analyzer service to complete telemetry subproject
akuniutka/plus-smart-home-tech pull request #5
Opened 2024-12-29 19:55 UTC by akuniutka

- Switch Collector from JSON to gRPC incoming message format
- Add Aggregator to make hub sensors data snapshots
- Add Analyzer to trigger device action when scenario condition met

2024-12-31 05:44 UTC, EugeneLenkevich requested changes
Привет, Андрей! Спасибо за PR.

Интересная работа, вижу активно используешь разные паттерны проектирования. Основные моменты, как ни странно - это логирование, отметил в комментариях.

Далее. Логика достаточно запутанная, тут бы было очень хорошо написать тесты. Один тест чисто на контроллер, то есть на сам контракт, сервис замокать с помощью Mockito. Мы такое делали с MockMvc. 
Второй тест - на сервис. Нам надо будет поднять контекст, замокать очередь, передать объект (в идеале всех типов, а совсем в идеале чтобы доступные варианты подтягивались автоматически, тогда у нас тест будет падать когда добавили новый объект, но не добавили в стратегию или что там у нас) через сервис и убедиться что сообщение ушло в мок очереди 

![image](https://github.com/user-attachments/assets/9ab2af82-fc25-47a2-b21a-fc8237a87403)

![image](https://github.com/user-attachments/assets/f3b07516-69b3-4dc6-b03e-6aa69449427d)

https://habr.com/ru/articles/444982/

На тестах не настаиваю, но будет очень круто если получится их сделать. Все эти интеграции очень сложно вручную отлаживать, а если мы говорим о микросервисах то это может быть сущим кошмаром так как сервисов много, сообщений логов тьма и разобраться что куда и откуда та еще задача. Однако такой тест еще на этапе сборки отловит несоответствия, это будет проще и быстрее :)

2024-12-31 05:44 UTC, EugeneLenkevich commented on telemetry/collector/src/main/java/ru/yandex/practicum/telemetry/collector/service/sender/hub/HubEventSenderImpl.java
> +        log.debug("Sent hub event to topic [{}]: {}", topic, event);
А давай сделаем логи вот в таком виде
log.info "Sent hub event, id={}, timestamp, другие основные параметры "
log.debug event= {}

И добавим их во все ключевые точки, такие как прием события через контроллер, отправка и получение события из кафки. Сами события логируем под debug, как ты и делаешь, тут все верно, иначе у нас лог будет огромным. Но на проде у нас дебаг будет выключен и диагностировать проблемы будет проблематично :)

Так нам будет проще отслеживать ошибки во время работы приложения, сможем быстрее локализовать проблему

2024-12-31 05:44 UTC, EugeneLenkevich commented on telemetry/hub-router/src/main/java/ru/yandex/practicum/telemetry/router/controller/DeviceActionController.java
> +            log.info("Data received => {}", request);
Под info можно вывести краткую информацию, какие то базовые идентификаторы, чтобы по ним по логу же и искать :)

2024-12-31 05:44 UTC, EugeneLenkevich commented on telemetry/serialization/avro-schemas/src/main/java/ru/yandex/practicum/kafka/telemetry/client/KafkaListener.java
> +        synchronized (lock) {
Я может не до конца разобрался, но вижу несколько моментов
1. А нет ли тут некоторого заката солнца вручную, судя по всему листенер мы создаем в спринговой конфигурации, будет ли в этот момент асинхронный режим, не берем ли мы обязанность спринга по разруливанию процесса созданию бинов на себя 
2. Далее, если решаем что синхронизация нам нужна (хотя, на самом деле она не помешает, бины создаются один раз) не проще сами методы сделать synchronized и избавится от lock, все равно блоки синхронизации совпадают с самими методами :)

2025-01-09 20:43 UTC, akuniutka commented
Привет, Евгений!

Я пока не сделал тесты на:
- сервис Analyzer,
- классы KafkaListener и KafkaSender,
- передачу и получение сообщений из тестовой Kafka (интеграционные).

Думаю над тем, как разбить Analyzer на модули поменьше, в идеале сфокусированные на одной функции, чтобы их было легче тестировать. После этого напишу оставшиеся тесты.

2025-01-10 04:53 UTC, EugeneLenkevich approved these changes
Спасибо за доработку, очень интересно получается. В целом все верно, но главное, в итоге, все не переусложнить :)
Работу принимаю, понятно что еще как то классы реорганизовать или еще тестов придумать - этот процесс бесконечен, в любом случае она сделана шире рамок самой постановки, ну и с Наступившими!

2025-01-10 10:27 UTC, merged